{
  "sksl": {
    "entrypoint": "BlackHoleRaymarcher3BufferA_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform float iTime;\nuniform float iFrame;\nuniform vec4 iMouse;\nuniform vec4 iChannelWrap;\nuniform vec4 iChannelFilter;\nuniform vec2 iChannelResolution0;\nuniform vec2 iChannelResolution1;\nuniform vec2 iChannelResolution2;\nuniform vec2 iChannelResolution3;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_flutter_local_mainImage(out vec4 pixVector, vec2 fragCoord)\n{\n    vec2 newCam = vec2(-5.0, 0.0);\n    if (all(equal(iMouse.xy, vec2(0.0))))\n    {\n        newCam = vec2(-1.60000002384185791015625, 0.550000011920928955078125);\n    }\n    newCam.y += (((-0.1500000059604644775390625) * sin((iTime + 15.0) / 15.0)) - 0.20000000298023223876953125);\n    vec2 pixAxis = ((newCam + ((vec2(8.0, 3.5) * iMouse.xy) / iResolution)) - vec2(0.5)) + (((vec2(0.5) + fragCoord) * 1.0471980571746826171875) / vec2(iResolution.x));\n    pixVector = vec4(pixAxis, 0.0, 1.0);\n}\n\nvoid FLT_main()\n{\n    float keep = (((((((((((iFrame + iMouse.x) + iTime) + iResolution.x) + iChannelWrap.x) + iChannelResolution0.x) + iChannelResolution0.y) + iChannelResolution1.x) + iChannelResolution1.y) + iChannelResolution2.x) + iChannelResolution2.y) + iChannelResolution3.x) + iChannelResolution3.y;\n    vec2 fragCoord_1 = FLT_flutter_local_FlutterFragCoord();\n    vec2 param_1 = fragCoord_1;\n    vec4 param;\n    FLT_flutter_local_mainImage(param, param_1);\n    fragColor = param;\n    if (keep < (-100000002004087734272.0))\n    {\n        fragColor += vec4(keep);\n    }\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "iTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "iFrame",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "iMouse",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "iChannelWrap",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "iChannelFilter",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "iChannelResolution0",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 7,
        "name": "iChannelResolution1",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 8,
        "name": "iChannelResolution2",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 9,
        "name": "iChannelResolution3",
        "rows": 2,
        "type": 10
      }
    ]
  }
}